### ISSUE TITLE
PermissionError: [WinError 5] Access is denied when running update.py

### ISSUE THREAD

**Issue by eddyv19** [bmd-studio/stm32-for-vscode#40]
Not an expert here. Keep getting windows permision error. Tried to run from a cmd shell in admin mode with no luck....

Eddy@DESKTOP-TIO8A3R MINGW32 /c/Users/Eddy/Dropbox/STM32CubeIDE/workspace_1.1.0/TrySTMVsCode
$ "C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python36_64/python.exe" c:/Users/Eddy/Dropbox/STM32CubeIDE/workspace_1.1.0/TrySTMVsCode/ideScripts/update.py
Update started.

Existing '.vscode' folder used.
One STM32CubeMX file found: Laps_v1.ioc
Existing 'Makefile' file will be restored from 'Makefile.backup'.
Copy of file (new name: Makefile): c:/Users/Eddy/Dropbox/STM32CubeIDE/workspace_1.1.0/TrySTMVsCode/Makefile.backup
Makefile 'print-variable' function added.
Valid 'buildData.json' file found.
Valid 'toolsPaths.json' file found.
'toolsPaths.json' file updated!

ERROR (0 seconds).
Unexpected error occured during 'Update' procedure. Exception:
Traceback (most recent call last):
  File "c:/Users/Eddy/Dropbox/STM32CubeIDE/workspace_1.1.0/TrySTMVsCode/ideScripts/update.py", line 56, in <module>
    makefileData = makefile.getMakefileData(makeExePath, gccExePath)
  File "c:\Users\Eddy\Dropbox\STM32CubeIDE\workspace_1.1.0\TrySTMVsCode\ideScripts\updateMakefile.py", line 109, in getMakefileData
    projectName = self.getMakefileVariable(makeExePath, gccExePath, self.mkfStr.projectName)[0]
  File "c:\Users\Eddy\Dropbox\STM32CubeIDE\workspace_1.1.0\TrySTMVsCode\ideScripts\updateMakefile.py", line 382, in getMakefileVariable
    proc = Popen(arguments, stdout=PIPE)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
PermissionError: [WinError 5] Access is denied

**Comment by eddyv19** [comment]
Sorry posted this in the wrong place
